json: Produce better errors when the source document unexpectedly ends
This happens either when there's some document context, but it's just
whitespace, or when the document is legitimately truncated.  I recently
observed this error in production.

Notably, adding this handling prevents IndexError exceptions in
__str__() because in cases of unexpected EOF, self.pos is not a valid
zero-based index.  Such IndexError exceptions manifested as:

    id3c.json.JSONDecodeError: <unprintable JSONDecodeError object>

when our exception object was printed.