Add APIJsonDecodeError to log the response text
When fetching REDCap records, raise the custom `APIJsonDecodeError`
error so that we log the text that is failing JSON decoding. This will
help us continue the investigation with ITHS.

With the response context set to b'abc' to simulate the error:
Currently we see logged:
Exception has occurred: JSONDecodeError
Expecting value: line 1 column 1 (char 0)

With this commit we will see:
Exception has occurred: APIJsonDecodeError
Error: 'Expecting value' Text to decode: 'abc'