Resolve ImportError when running id3c.api by moving an import
The import of id3c.cli.utils from id3c.db.session caused an ImportError
due to circular dependencies when it was the result of loading id3c.api:

  File "…/lib/id3c/api/__init__.py", line 7, in <module>
    from .routes import blueprints
  File "…/lib/id3c/api/routes.py", line 8, in <module>
    from . import datastore
  File "…/lib/id3c/api/datastore.py", line 11, in <module>
    from ..db.session import DatabaseSession
  File "…/lib/id3c/db/__init__.py", line 14, in <module>
    from .session import DatabaseSession
  File "…/lib/id3c/db/session.py", line 14, in <module>
    from ..cli.utils import running_command_name
  File "…/lib/id3c/cli/__init__.py", line 21, in <module>
    from .command import *
  File "…/lib/id3c/cli/command/__init__.py", line 12, in <module>
    from id3c.db.session import DatabaseSession
  ImportError: cannot import name 'DatabaseSession'

In the short term, avoid this by doing the import after module load time.
tests/web-api.py now passes.  In the longer term, the tangled imports of
id3c.cli and command submodules should be simplified and do less at module load
time.